spring:
  profiles:
    active: mock
  liquibase:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration
      - org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration

server:
  port: 8080

mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-handlers-package: org.apache.ibatis.type
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: db
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/enrollment_demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-handlers-package: org.apache.ibatis.type
  configuration:
    map-underscore-to-camel-case: true
