spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/enrollment_demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-handlers-package: org.mybatis.type
  configuration:
    map-underscore-to-camel-case: true
